# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
DatabaseCleaner.clean_with(:truncation)

Band.create(band_name: 'Falsetta', city: 'Austin', state: 'TX', start_date: Date.new(2008,2,1))
Band.create(band_name: '', city: '', state: '', start_date: '')
Band.create(band_name: '', city: '', state: '', start_date: '')
Band.create(band_name: '', city: '', state: '', start_date: '')
Band.create(band_name: '', city: '', state: '', start_date: '')
Band.create(band_name: '', city: '', state: '', start_date: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Album.create(title: '', release_date: '', type: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Musician.create(first_name: '', twitter_name: '')
Instrument.
